{%set build = 4 %}
{%set version = '0.1.0' %}

package:
  name: neurokernel_deps
  version: {{version}}

about:
  home: https://github.com/neurokernel/neurokernel_deps_conda_recipe
  license: BSD License
  summary: "Neurokernel dependencies meta package."

requirements:
  run:
    - 'bidict >=0.3.1'
    - 'cython >=0.22'
    - 'dill >=0.2.4'
    - 'futures >=3.0.0'
    - 'h5py >=2.5.0'
    - 'lxml >=3.3.0'
    - 'markupsafe >=0.23'
    - 'matplotlib >=1.4.3'
    - 'mock >=1.3.0'
    - 'mpi4py >=2.0.0'
    - 'msgpack-numpy >=0.3.5'
    - 'networkx >=1.9.1'
    - 'nose >=1.3.7'
    - 'numpy >=1.9.2'
    - 'openmpi >=1.8.8'
    - 'pandas >=0.16.0'
    - 'ply >=3.4'
    - 'pytest >=2.7.0'
    - 'psutil >=2.2.1'
    - 'pycuda >=2015.1'
    - 'pyzmq >=14.5.0'
    - 'pytables >=3.2.0'
    - 'python >=2.7.9'
    - 'scipy >=0.11.0'
    - 'setuptools >=17.1'
    - 'shutilwhich >=1.1.0'
    - 'twiggy >=0.4.7'
    
build:
  number: {{build}}
  string: {{build}}
